[package]
name = "gitlab_client_example_basic_reqwest"
edition = "2021"
publish = false

[dependencies]
futures = "0.3.30"
gitlab_client = { path = "../..", features = ["reqwest"] }
tokio = { version = "1.37.0", features = ["full"] }
